services:
  - type: web
    name: induced-backend
    env: node
    buildCommand: npm install && npm run build
    startCommand: node dist/app.js
    nodeVersion: 22.14.0
    envVars:
      - key: NODE_ENV
        value: production
